### ISSUE TITLE
[Bug] Wrong instructions for file extensions

### ISSUE THREAD

**Issue by PeppeL-G** [keyoti/VSCode-ChangeAllEOL#11]
When running the command in VS Code and asked to enter file extensions, the placeholder shows one should add a comma and a space between the file extensions:

https://github.com/keyoti/VSCode-ChangeAllEOL/blob/b10944cddc9e700b2f798d053ba3be35f2e75d40/src/extension.ts#L56

But according to the implementation one should only add a comma.

https://github.com/keyoti/VSCode-ChangeAllEOL/blob/b10944cddc9e700b2f798d053ba3be35f2e75d40/src/extension.ts#L75

https://github.com/keyoti/VSCode-ChangeAllEOL/blob/b10944cddc9e700b2f798d053ba3be35f2e75d40/src/extension.ts#L24

Otherwise this extension worked great for me, thank you!

**Comment by keyoti** [comment]
It's updated to v0.0.4 on the VS Code marketplace so that spaces and commas are accepted.  Thanks!
