### ISSUE TITLE
Assistance for a VSCode newbie

### ISSUE THREAD

**Issue by pelicanmedia** [keyoti/VSCode-ChangeAllEOL#7]
Hi there,

I'm new to using extensions in VSCode. I have just downloaded your extension and tried to convert all the files in my project from CRLF to LF, but it seems that it will only convert a single file that I have open. 

When following your instructions:
"_Open the command pallette (CTRL+SHIFT+P) and type "Change All End Of Line Sequence"._" - That's fine I get that.
"_You will be asked for the file types that should have their line endings changed (directories starting with '.' are ignored)._" - I do not get this option.

If I have a single file open I get the choice of CRLF or LF, but only on a single file.
What do I need to have selected for it to convert ALL of the files in my project?

Thank you.

**Comment by keyoti** [comment]
Hi, are you sure that the command you chose was not "Change End Of Line Sequence" instead of "Change All End Of Line Sequence"?  Because the former is the built-in command and would behave as you say, changing only one file.

**Comment by pelicanmedia** [comment]
Ah yes, 🤦‍♂️ Oops sorry!
Got there eventually... No spaces in the file types and folders boxes also!
Thanks for the quick response!
