### ISSUE TITLE
0 files changed if white/blacklist is left blank

### ISSUE THREAD

**Issue by hypermaq** [keyoti/VSCode-ChangeAllEOL#8]
If I set the "file types to convert" to .py, and then leave the white/blacklist empty, I expected the add-in to change all .py files in the workspace.
However, it seems that causes it to change no file at all.

Picking a bogus blacklist entry such as !doesntexist solves this.

Not sure if this is a bug or I'm using this wrong though...

**Comment by keyoti** [comment]
Thanks @hypermaq I will publish the fix today on marketplace.
